import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/index.module.css'
import HeaderContainer from '../components/Containers/HeaderContainer'
import IndexContainer from '../components/Containers/indexContainer'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>ShopSmart | Главная</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Icon2.png" />
      </Head>
      <IndexContainer>
        <HeaderContainer>
         

        </HeaderContainer>
      </IndexContainer>
    </>
  )
}

export default Home
