import React from 'react'
import UserProfileContainer from '../components/Containers/UserProfileContainer'
import Head from 'next/head'

const user = () => {
  return (
    <>
     <Head>
        <title>ShopSmart | Пользователь</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Icon2.png" />
      </Head>
    <UserProfileContainer >
        
    </UserProfileContainer>
    </>
  )
}

export default user